name: nut_ecom_app
description: Internal app for managing order data
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # HTTP Client
  http: ^1.6.0
  dio: ^5.4.0
  http_parser: ^4.0.2
  
  # Firebase
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  
  # UI
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  flutter_spinkit: ^5.2.0
  google_fonts: ^6.1.0
  lottie: ^3.1.0
  mobile_scanner: ^7.1.3
  
  # Utilities
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  image_picker: ^1.0.4
  google_sign_in: ^7.2.0
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # Fonts
  fonts:
    - family: AlumniSans
      fonts:
        - asset: fonts/AlumniSans-VariableFont_wght.ttf
        - asset: fonts/AlumniSans-Italic-VariableFont_wght.ttf
          style: italic
    - family: AndadaPro
      fonts:
        - asset: fonts/AndadaPro-VariableFont_wght.ttf
        - asset: fonts/AndadaPro-Italic-VariableFont_wght.ttf
          style: italic
    - family: Anaheim
      fonts:
        - asset: fonts/Anaheim-VariableFont_wght.ttf
    - family: poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Italic.ttf
          style: italic
  
  # Assets
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/logo.svg
    - assets/animations/
    - assets/animations/Scan_qr_code.json
